version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "63798:6379"

  docling:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STORAGE_ROOT_PATH=/app/storage
      - HF_HOME=/app/cache/huggingface
      - HF_HUB_CACHE=/app/cache/huggingface/hub
    depends_on:
      - redis
    volumes:
      - ./storage:/app/storage
      - ./cache:/app/cache

#  nginx:
#    image: nginx:latest
#    ports:
#      - "9999:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - docling