services:
  redis:
    image: valkey/valkey:latest
    ports:
      - "16377:6379"
#    hostname: cache
    command: redis-server --appendonly yes
    volumes:
      - cache-data:/data
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 1s
      timeout: 3s
      retries: 30
  db:
    image: postgres:latest
    ports:
      - "15433:5432"
    hostname: db
    environment:
      POSTGRES_PASSWORD: "app"
      POSTGRES_USER: "app"
      POSTGRES_DB: "app"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - app
      interval: 2s
      timeout: 3s
      retries: 40

  docling:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STORAGE_ROOT_PATH=/app/storage
      - HF_HOME=/app/storage/huggingface
      - HF_HUB_CACHE=/app/storage/huggingface/hub
      - DATABASE_ECHO=true
      - DATABASE_POOL_DISABLE=false
      - DATABASE_POOL_MAX_OVERFLOW=5
      - DATABASE_POOL_SIZE=5
      - DATABASE_POOL_TIMEOUT=30
      - DATABASE_URL=postgresql+asyncpg://app:app@db:5432/app
    depends_on:
      - redis
    volumes:
      - ./storage:/app/storage
volumes:
  db-data: {}
  cache-data: {}
