version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "63798:6379"

  docling:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "celery_app", "worker", "--loglevel=info"]
    depends_on:
      - redis

#  nginx:
#    image: nginx:latest
#    ports:
#      - "9999:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - docling