FROM python:3.12-slim

WORKDIR /workspace

RUN pip install litestar "advanced-alchemy[uuid]" asyncpg pydantic PyPDF2 celery redis

COPY src /workspace/src
COPY docker/pyproject.docling.toml /workspace/pyproject.toml
COPY resources /workspace/resources
COPY package.json /workspace/package.json

RUN pip install -e .

CMD ["uvicorn", "app.asgi:app", "--host", "0.0.0.0", "--port", "8000"]
